{{- if .Values.jobsProcessing.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ror.jobProcessingName" . }}
  labels:
    {{- include "ror.labels" . | nindent 4 }}
    app.kubernetes.io/component: jobs
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.jobsProcessing.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ror.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ror.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: jobs
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ror.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ toYaml .Values.jobsProcessing.command | nindent 12 }}
          env: 
            {{- include "ror.env" .Values | nindent 12 }}
          {{/*ports:*/}}
            {{/*- name: http*/}}
              {{/*containerPort: 3000 # {{ .Values.service.port }}*/}}
              {{/*protocol: TCP*/}}
          {{/*livenessProbe:*/}}
            {{/*{{- toYaml .Values.livenessProbe | nindent 12 }}*/}}
          resources:
            {{- toYaml .Values.jobsProcessing.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.jobsProcessing.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.jobsProcessing.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
